// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, http, partials;

  http = require('http');

  partials = require('express-partials');

  express = require('express');

  app = express();

  app.set("port", process.env.PORT);

}).call(this);
